"""
Configuration for the standalone machine-learning training and validation project.

Normal usage from this folder:

    python main.py

The scripts do not import the feature-selection project. They reuse the same
chronological split strategy, but assume feature selection has already been
reviewed and that the prepared features below are the approved feature sets.
"""
from pathlib import Path

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
PROJECT_DIR = Path(__file__).resolve().parent

# The resolver accepts either a file or a directory. If this is a directory, the
# loader searches for snapshot_dataframe.parquet, snapshot_dataframe.csv, or the
# first parquet/csv file in the folder.
INPUT_DATA_PATH = PROJECT_DIR.parent / "data_preparation" / "output" / "snapshot_dataframe"

# All generated CSV, JSON, model, and validation outputs are written here.
OUTPUT_DIR = PROJECT_DIR / "output"

# -----------------------------------------------------------------------------
# Dataset columns
# -----------------------------------------------------------------------------
TARGET_COL = "claim_next_45d"
DATE_COL = "snapshot_date"
ID_COLS = ["model_id"]
SECONDARY_SORT_COLS = ["model_id"]

# Optional source columns to drop immediately after loading, before splitting.
SOURCE_COLUMNS_TO_DROP_BEFORE_MODELING = []

# -----------------------------------------------------------------------------
# Outer chronological split: train / validation / test
# -----------------------------------------------------------------------------
# These are treated as weights and normalized internally if they do not sum to 1.
TRAIN_RATIO = 0.70
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15

# -----------------------------------------------------------------------------
# Expanding-window CV inside training_main only
# -----------------------------------------------------------------------------
CV_N_SPLITS = 4
CV_VALIDATION_WINDOW_DAYS = 45
CV_GAP_DAYS = 45
CV_MIN_TRAIN_ROWS = 1000
CV_MIN_VALIDATION_ROWS = 200
CV_MIN_POSITIVES_IN_TRAIN = 10
CV_MIN_POSITIVES_IN_VALIDATION = 5

# CV threshold metrics are reported for context only. Hyperparameter selection
# uses mean PR-AUC / average precision, not F2.
CV_DEFAULT_THRESHOLD = 0.50
CV_MAX_FLAGGED_RATE_FOR_BEST_F2 = 0.15

# -----------------------------------------------------------------------------
# Preprocessing
# -----------------------------------------------------------------------------
NUMERIC_IMPUTE_STRATEGY = "median"
CATEGORICAL_IMPUTE_STRATEGY = "most_frequent"
ONE_HOT_ENCODE_CATEGORICAL = True
ERROR_ON_MISSING_SOURCE_FEATURES = True

# If a selected prepared feature is not generated by the preprocessor for the
# current training data, add it as an all-zero column. This is useful for one-hot
# categories absent in a specific training period. Missing source columns are
# still controlled by ERROR_ON_MISSING_SOURCE_FEATURES.
ADD_MISSING_PREPARED_FEATURES_AS_ZERO = False

# -----------------------------------------------------------------------------
# Feature variants
# -----------------------------------------------------------------------------
# Model A = all 93 prepared features that survived feature-selection review.
# Model B = Model A minus high-confidence drop candidates.
# Model C = Model B minus additional review/drop candidates, including the
# redundant has_fault_90d flag.
MODEL_A_PREPARED_FEATURES = ['num__days_since_last_fault',
 'num__smr_latest_before_snapshot',
 'num__days_since_last_claim',
 'num__fluid_sample_count_365d',
 'num__days_since_last_reset',
 'num__prior_claim_count_365d',
 'num__Cu_Copper_PPM',
 'num__monitor_reset_count_180d',
 'num__prior_claim_count_180d',
 'num__Fe_Iron_PPM',
 'num__days_since_last_severe_fault',
 'num__avg_remaining_hours',
 'num__maintenance_events_180d',
 'num__max_log_occurrence_90d',
 'num__maintenance_events_90d',
 'num__Soot_Soot_PERCENT',
 'num__avg_working_hours_per_actual_work_day_90d',
 'num__avg_event_evidence_score_90d',
 'num__fault_smr_delta_90d',
 'num__travel_share_of_working_hours_90d',
 'num__Sn_Tin_PPM',
 'num__smr_latest_hours',
 'num__Pb_Lead_PPM',
 'num__Ag_Silver_PPM',
 'num__monitor_reset_count_90d',
 'num__top_component_fault_ratio_90d',
 'num__unique_fault_code_count_90d',
 'num__smr_delta_30d',
 'num__engine_idling_share_90d',
 'num__min_remaining_hours',
 'num__faults_per_100_hours',
 'num__occurrence_severity_score_90d',
 'num__Ti_Titanium_PPM',
 'num__moving_back_forth_to_travel_ratio_90d',
 'num__manual_variable_shift_hours_sum_90d',
 'num__engine_fault_count_90d',
 'num__K_Potassium_PPM',
 'num__days_since_last_smr',
 'num__engine_observed_day_count_90d',
 'num__urea_scr_system_reset_count_180d',
 'num__engine_running_day_ratio_90d',
 'num__smr_delta_90d',
 'num__Soot_Soot_Abs_cm',
 'num__repeat_fault_ratio_90d',
 'num__max_context_evidence_score_90d',
 'num__mechanical_fault_count_90d',
 'num__working_hours_sum_7d',
 'num__unique_claim_type_count_365d',
 'num__unique_component_count_90d',
 'num__moderate_fault_count_90d',
 'num__Fuel_Fuel_PERCENT',
 'num__prior_claim_count_90d',
 'num__action_L03_count_90d',
 'num__strong_fault_count_90d',
 'num__electrical_fault_count_90d',
 'num__smr_since_last_reset',
 'num__fault_count_30d',
 'num__fuel_actual_work_conflict_count_90d',
 'num__action_L04_count_90d',
 'num__fault_count_7d',
 'num__smr_delta_7d',
 'num__fault_growth_rate',
 'num__auto_quick_shift_hours_sum_90d',
 'num__V_Vanadium_PPM',
 'num__action_L01_count_90d',
 'cat__full_model_D71EXI_24',
 'num__workequipment_fault_count_90d',
 'num__Ni_Nickel_PPM',
 'num__maintenance_due_or_overdue_ratio',
 'num__max_action_level_90d',
 'num__working_hours_sum_90d',
 'num__electrical_fault_count_30d',
 'num__powertrain_fault_count_90d',
 'num__actual_work_day_ratio_change_30d_vs_90d',
 'num__has_fault_90d',
 'cat__full_model_D71PX_24',
 'num__fault_count_previous_30d',
 'num__mechanical_fault_count_30d',
 'num__Water_Water_PERCENT',
 'num__current_actual_work_streak_days',
 'num__Li_Lithium_PPM',
 'num__action_L02_count_90d',
 'num__due_now_item_count',
 'num__throttle_full_share_change_30d_vs_90d',
 'num__final_drive_overdue_item_count',
 'num__cooling_fault_count_90d',
 'cat__full_model_D71EX_24',
 'cat__full_model_D71PX_24E0',
 'num__working_hours_rate_change_30d_vs_90d',
 'cat__full_model_D71PXI_24',
 'num__urea_scr_system_overdue_item_count',
 'num__overdue_item_count',
 'num__transmission_overdue_item_count']

MODEL_B_DROP_PREPARED_FEATURES = ['num__transmission_overdue_item_count',
 'num__overdue_item_count',
 'num__urea_scr_system_overdue_item_count',
 'num__cooling_fault_count_90d',
 'num__final_drive_overdue_item_count',
 'num__Li_Lithium_PPM',
 'num__current_actual_work_streak_days',
 'num__action_L02_count_90d',
 'num__due_now_item_count',
 'num__working_hours_rate_change_30d_vs_90d',
 'cat__full_model_D71PX_24E0',
 'cat__full_model_D71PXI_24',
 'num__maintenance_due_or_overdue_ratio',
 'num__powertrain_fault_count_90d']

MODEL_C_ADDITIONAL_DROP_PREPARED_FEATURES = ['num__actual_work_day_ratio_change_30d_vs_90d',
 'num__mechanical_fault_count_30d',
 'num__strong_fault_count_90d',
 'num__smr_since_last_reset',
 'num__auto_quick_shift_hours_sum_90d',
 'num__fault_growth_rate',
 'num__workequipment_fault_count_90d',
 'num__Water_Water_PERCENT',
 'num__Fuel_Fuel_PERCENT',
 'num__moving_back_forth_to_travel_ratio_90d',
 'num__fuel_actual_work_conflict_count_90d',
 'cat__full_model_D71EX_24',
 'cat__full_model_D71PX_24',
 'num__has_fault_90d']

PREPARED_TO_SOURCE_FEATURE = {'cat__full_model_D71EXI_24': 'full_model',
 'cat__full_model_D71EX_24': 'full_model',
 'cat__full_model_D71PXI_24': 'full_model',
 'cat__full_model_D71PX_24': 'full_model',
 'cat__full_model_D71PX_24E0': 'full_model',
 'num__Ag_Silver_PPM': 'Ag_Silver_PPM',
 'num__Cu_Copper_PPM': 'Cu_Copper_PPM',
 'num__Fe_Iron_PPM': 'Fe_Iron_PPM',
 'num__Fuel_Fuel_PERCENT': 'Fuel_Fuel_PERCENT',
 'num__K_Potassium_PPM': 'K_Potassium_PPM',
 'num__Li_Lithium_PPM': 'Li_Lithium_PPM',
 'num__Ni_Nickel_PPM': 'Ni_Nickel_PPM',
 'num__Pb_Lead_PPM': 'Pb_Lead_PPM',
 'num__Sn_Tin_PPM': 'Sn_Tin_PPM',
 'num__Soot_Soot_Abs_cm': 'Soot_Soot_Abs_cm',
 'num__Soot_Soot_PERCENT': 'Soot_Soot_PERCENT',
 'num__Ti_Titanium_PPM': 'Ti_Titanium_PPM',
 'num__V_Vanadium_PPM': 'V_Vanadium_PPM',
 'num__Water_Water_PERCENT': 'Water_Water_PERCENT',
 'num__action_L01_count_90d': 'action_L01_count_90d',
 'num__action_L02_count_90d': 'action_L02_count_90d',
 'num__action_L03_count_90d': 'action_L03_count_90d',
 'num__action_L04_count_90d': 'action_L04_count_90d',
 'num__actual_work_day_ratio_change_30d_vs_90d': 'actual_work_day_ratio_change_30d_vs_90d',
 'num__auto_quick_shift_hours_sum_90d': 'auto_quick_shift_hours_sum_90d',
 'num__avg_event_evidence_score_90d': 'avg_event_evidence_score_90d',
 'num__avg_remaining_hours': 'avg_remaining_hours',
 'num__avg_working_hours_per_actual_work_day_90d': 'avg_working_hours_per_actual_work_day_90d',
 'num__cooling_fault_count_90d': 'cooling_fault_count_90d',
 'num__current_actual_work_streak_days': 'current_actual_work_streak_days',
 'num__days_since_last_claim': 'days_since_last_claim',
 'num__days_since_last_fault': 'days_since_last_fault',
 'num__days_since_last_reset': 'days_since_last_reset',
 'num__days_since_last_severe_fault': 'days_since_last_severe_fault',
 'num__days_since_last_smr': 'days_since_last_smr',
 'num__due_now_item_count': 'due_now_item_count',
 'num__electrical_fault_count_30d': 'electrical_fault_count_30d',
 'num__electrical_fault_count_90d': 'electrical_fault_count_90d',
 'num__engine_fault_count_90d': 'engine_fault_count_90d',
 'num__engine_idling_share_90d': 'engine_idling_share_90d',
 'num__engine_observed_day_count_90d': 'engine_observed_day_count_90d',
 'num__engine_running_day_ratio_90d': 'engine_running_day_ratio_90d',
 'num__fault_count_30d': 'fault_count_30d',
 'num__fault_count_7d': 'fault_count_7d',
 'num__fault_count_previous_30d': 'fault_count_previous_30d',
 'num__fault_growth_rate': 'fault_growth_rate',
 'num__fault_smr_delta_90d': 'fault_smr_delta_90d',
 'num__faults_per_100_hours': 'faults_per_100_hours',
 'num__final_drive_overdue_item_count': 'final_drive_overdue_item_count',
 'num__fluid_sample_count_365d': 'fluid_sample_count_365d',
 'num__fuel_actual_work_conflict_count_90d': 'fuel_actual_work_conflict_count_90d',
 'num__has_fault_90d': 'has_fault_90d',
 'num__maintenance_due_or_overdue_ratio': 'maintenance_due_or_overdue_ratio',
 'num__maintenance_events_180d': 'maintenance_events_180d',
 'num__maintenance_events_90d': 'maintenance_events_90d',
 'num__manual_variable_shift_hours_sum_90d': 'manual_variable_shift_hours_sum_90d',
 'num__max_action_level_90d': 'max_action_level_90d',
 'num__max_context_evidence_score_90d': 'max_context_evidence_score_90d',
 'num__max_log_occurrence_90d': 'max_log_occurrence_90d',
 'num__mechanical_fault_count_30d': 'mechanical_fault_count_30d',
 'num__mechanical_fault_count_90d': 'mechanical_fault_count_90d',
 'num__min_remaining_hours': 'min_remaining_hours',
 'num__moderate_fault_count_90d': 'moderate_fault_count_90d',
 'num__monitor_reset_count_180d': 'monitor_reset_count_180d',
 'num__monitor_reset_count_90d': 'monitor_reset_count_90d',
 'num__moving_back_forth_to_travel_ratio_90d': 'moving_back_forth_to_travel_ratio_90d',
 'num__occurrence_severity_score_90d': 'occurrence_severity_score_90d',
 'num__overdue_item_count': 'overdue_item_count',
 'num__powertrain_fault_count_90d': 'powertrain_fault_count_90d',
 'num__prior_claim_count_180d': 'prior_claim_count_180d',
 'num__prior_claim_count_365d': 'prior_claim_count_365d',
 'num__prior_claim_count_90d': 'prior_claim_count_90d',
 'num__repeat_fault_ratio_90d': 'repeat_fault_ratio_90d',
 'num__smr_delta_30d': 'smr_delta_30d',
 'num__smr_delta_7d': 'smr_delta_7d',
 'num__smr_delta_90d': 'smr_delta_90d',
 'num__smr_latest_before_snapshot': 'smr_latest_before_snapshot',
 'num__smr_latest_hours': 'smr_latest_hours',
 'num__smr_since_last_reset': 'smr_since_last_reset',
 'num__strong_fault_count_90d': 'strong_fault_count_90d',
 'num__throttle_full_share_change_30d_vs_90d': 'throttle_full_share_change_30d_vs_90d',
 'num__top_component_fault_ratio_90d': 'top_component_fault_ratio_90d',
 'num__transmission_overdue_item_count': 'transmission_overdue_item_count',
 'num__travel_share_of_working_hours_90d': 'travel_share_of_working_hours_90d',
 'num__unique_claim_type_count_365d': 'unique_claim_type_count_365d',
 'num__unique_component_count_90d': 'unique_component_count_90d',
 'num__unique_fault_code_count_90d': 'unique_fault_code_count_90d',
 'num__urea_scr_system_overdue_item_count': 'urea_scr_system_overdue_item_count',
 'num__urea_scr_system_reset_count_180d': 'urea_scr_system_reset_count_180d',
 'num__workequipment_fault_count_90d': 'workequipment_fault_count_90d',
 'num__working_hours_rate_change_30d_vs_90d': 'working_hours_rate_change_30d_vs_90d',
 'num__working_hours_sum_7d': 'working_hours_sum_7d',
 'num__working_hours_sum_90d': 'working_hours_sum_90d'}

MODEL_B_PREPARED_FEATURES = [
    f for f in MODEL_A_PREPARED_FEATURES if f not in set(MODEL_B_DROP_PREPARED_FEATURES)
]
MODEL_C_PREPARED_FEATURES = [
    f
    for f in MODEL_A_PREPARED_FEATURES
    if f not in set(MODEL_B_DROP_PREPARED_FEATURES)
    and f not in set(MODEL_C_ADDITIONAL_DROP_PREPARED_FEATURES)
]

# Model D = Model C plus protected machine-context features. This keeps the
# lean feature set from Model C while retaining broader model/product context.
# Do not use unique equipment serial IDs as one-hot model inputs unless you have
# explicitly validated that this does not create memorization/leakage.
MACHINE_CONTEXT_SOURCE_FEATURES = ["full_model"]
MACHINE_CONTEXT_PREPARED_FEATURE_PREFIXES = ["cat__full_model_"]
PROTECTED_MACHINE_CONTEXT_PREPARED_FEATURES = [
    f
    for f in MODEL_A_PREPARED_FEATURES
    if PREPARED_TO_SOURCE_FEATURE.get(f) in set(MACHINE_CONTEXT_SOURCE_FEATURES)
    or any(f.startswith(prefix) for prefix in MACHINE_CONTEXT_PREPARED_FEATURE_PREFIXES)
]
MODEL_D_PREPARED_FEATURES = [
    f
    for f in MODEL_A_PREPARED_FEATURES
    if f in set(MODEL_C_PREPARED_FEATURES)
    or f in set(PROTECTED_MACHINE_CONTEXT_PREPARED_FEATURES)
]

FEATURE_SETS = {
    "A": MODEL_A_PREPARED_FEATURES,
    "B": MODEL_B_PREPARED_FEATURES,
    "C": MODEL_C_PREPARED_FEATURES,
    "D": MODEL_D_PREPARED_FEATURES,
}

# Run CV and validation training for these variants. Test evaluation should be
# done only for the final selected variant unless EVALUATE_TEST_FOR_ALL_VARIANTS
# is intentionally set to True.
MODEL_VARIANTS_TO_RUN = ["A", "B", "C", "D"]

# If True, choose the final test-evaluated variant using validation F2 after the
# max flagged-rate constraint. If False, FINAL_MODEL_VARIANT is used.
AUTO_SELECT_FINAL_VARIANT_BY_VALIDATION_F2 = True
FINAL_MODEL_VARIANT = "A"
EVALUATE_TEST_FOR_ALL_VARIANTS = False


# -----------------------------------------------------------------------------
# Optional reduced source snapshot export
# -----------------------------------------------------------------------------
# When enabled, 00_split_data.py saves a source-level snapshot dataframe reduced
# to the source columns required by one selected model variant. For Model D this
# means ID/date/target columns plus the original source columns that generate
# MODEL_D_PREPARED_FEATURES. One-hot prepared features such as cat__full_model_*
# are represented by their original source column, e.g. full_model.
SAVE_REDUCED_SNAPSHOT_DATAFRAME = False
REDUCED_SNAPSHOT_MODEL_VARIANT = "D"
REDUCED_SNAPSHOT_OUTPUT_FILENAME = "06_snapshot_dataframe_model_D_reduced.csv"
REDUCED_SNAPSHOT_INCLUDE_SPLIT_COLUMN = False

# -----------------------------------------------------------------------------
# XGBoost settings
# -----------------------------------------------------------------------------
RANDOM_STATE = 42
USE_SCALE_POS_WEIGHT = True

# Project default parameters for now. Later, add dictionaries to
# HYPERPARAMETER_GRID to tune with expanding-window CV. The selected parameter
# set is the one with the highest mean validation average_precision.
XGB_DEFAULT_PARAMS = {
    "n_estimators": 300,
    "max_depth": 4,
    "learning_rate": 0.05,
    "subsample": 0.85,
    "colsample_bytree": 0.85,
    "objective": "binary:logistic",
    "eval_metric": "aucpr",
    "tree_method": "hist",
    "random_state": RANDOM_STATE,
    "n_jobs": 1,
}

# Example for later tuning:
# HYPERPARAMETER_GRID = [
#     {"max_depth": 3, "learning_rate": 0.05, "n_estimators": 300},
#     {"max_depth": 4, "learning_rate": 0.03, "n_estimators": 500},
# ]
HYPERPARAMETER_GRID = []

# -----------------------------------------------------------------------------
# Validation threshold selection and reporting
# -----------------------------------------------------------------------------
THRESHOLD_BETA = 2.0
MAX_FLAGGED_RATE = 0.15
THRESHOLD_GRID_SIZE = 1001
THRESHOLD_MIN = 0.0
THRESHOLD_MAX = 1.0

# Snapshot-row top-K reports answer questions such as: if we flag the top 5%
# highest-risk snapshot rows, what recall and precision do we get?
TOP_K_RATES = [0.01, 0.02, 0.05, 0.10, 0.15, 0.20]

# Optional machine-level top-K reporting. This collapses repeated snapshots for
# the same machine into one machine-level risk score before ranking. It is often
# more actionable than snapshot-row top-K for inspection/worklist planning.
ENABLE_MACHINE_LEVEL_TOP_K = True
MACHINE_ID_COL = "model_id"
MACHINE_TOP_K_RATES = TOP_K_RATES
MACHINE_PROBABILITY_AGGREGATION = "max"  # allowed: "max", "mean", "latest"
MACHINE_TARGET_AGGREGATION = "max"       # allowed: "max", "latest"

# -----------------------------------------------------------------------------
# Output / persistence
# -----------------------------------------------------------------------------
SAVE_CV_PREDICTIONS = True
SAVE_VALIDATION_AND_TEST_PREDICTIONS = True
SAVE_FINAL_MODEL_ARTIFACTS = True
